"""Criação inicial de todas as tabelas do projeto

Revision ID: bf1794d056c9
Revises: 
Create Date: 2025-08-08 21:25:48.488788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf1794d056c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos_horarios',
    sa.Column('id_slot_horario', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_slot_horario')
    )
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cargo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_cargo')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('carga_horaria_semanal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rede_ensino', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('matricula', sa.String(length=11), nullable=True),
    sa.Column('id_cargo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('atualizado_em', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos_turmas',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_turma', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_aluno', 'id_turma', 'ano_letivo')
    )
    op.create_table('comunicacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_remetente', sa.Integer(), nullable=False),
    sa.Column('tipo_comunicacao', sa.Enum('Notificacao', 'Recomendacao'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('data_expiracao', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_remetente'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disponibilidade_professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_slot_horario', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('ano_letivo_referencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_professor'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_slot_horario'], ['alunos_horarios.id_slot_horario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_horaria_alocacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_turma', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('id_slot_horario', sa.Integer(), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_professor'], ['usuarios.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_sala'], ['salas.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_slot_horario'], ['alunos_horarios.id_slot_horario'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professores_disciplinas',
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_professor'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_professor', 'id_disciplina')
    )
    op.create_table('comunicacao_destinatarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_comunicacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario_destinatario', sa.Integer(), nullable=True),
    sa.Column('id_cargo_destinatario', sa.Integer(), nullable=True),
    sa.Column('id_turma_destinataria', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('data_leitura', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo_destinatario'], ['cargos.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_comunicacao'], ['comunicacoes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_turma_destinataria'], ['turmas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_destinatario'], ['usuarios.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicacao_destinatarios')
    op.drop_table('professores_disciplinas')
    op.drop_table('grade_horaria_alocacoes')
    op.drop_table('disponibilidade_professores')
    op.drop_table('comunicacoes')
    op.drop_table('alunos_turmas')
    op.drop_table('usuarios')
    op.drop_table('turmas')
    op.drop_table('salas')
    op.drop_table('instituicoes')
    op.drop_table('disciplinas')
    op.drop_table('cargos')
    op.drop_table('alunos_horarios')
    # ### end Alembic commands ###
